var levels = [
  ["shroom", "flower", "20coins", "shroom", "10coins", "star",
   "flower", "1up", "shroom", "10coins", "1up", "20coins",
   "star", "flower", "star", "shroom", "flower", "star"],
  ["shroom", "flower", "20coins", "flower", "10coins", "star",
   "20coins", "1up", "shroom", "10coins", "1up", "flower",
   "star", "shroom", "star", "shroom", "flower", "star"],
  ["shroom", "flower", "1up", "flower", "star", "star",
   "20coins", "star", "shroom", "10coins", "1up", "flower",
   "20coins", "shroom", "10coins", "shroom", "flower", "star"],
  ["flower", "10coins", "1up", "flower", "1up", "shroom",
   "star", "shroom", "20coins", "star", "shroom", "10coins",
   "star", "flower", "20coins", "shroom", "flower", "star"],
  ["flower", "20coins", "shroom", "star", "1up", "flower",
   "1up", "flower", "10coins", "shroom", "20coins", "star",
   "shroom", "10coins", "star", "shroom", "flower", "star"],
  ["flower", "star", "1up", "flower", "20coins", "shroom",
   "10coins", "shroom", "20coins", "1up", "shroom", "10coins",
   "star", "flower", "star", "shroom", "flower", "star"],
  ["flower", "star", "1up", "flower", "1up", "shroom",
   "10coins", "shroom", "flower", "star", "shroom", "10coins",
   "star", "20coins", "20coins", "shroom", "flower", "star"],
  ["1up", "shroom", "10coins", "shroom", "flower", "star",
   "shroom", "10coins", "star", "20coins", "20coins", "flower",
   "star", "1up", "flower", "shroom", "flower", "star"]
];